/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AiPocImport } from './routes/ai-poc'
import { Route as AboutImport } from './routes/about'

// Create/Update Routes

const AiPocRoute = AiPocImport.update({
  id: '/ai-poc',
  path: '/ai-poc',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/ai-poc': {
      id: '/ai-poc'
      path: '/ai-poc'
      fullPath: '/ai-poc'
      preLoaderRoute: typeof AiPocImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/ai-poc': typeof AiPocRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/ai-poc': typeof AiPocRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRoute
  '/ai-poc': typeof AiPocRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/ai-poc'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/ai-poc'
  id: '__root__' | '/about' | '/ai-poc'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  AiPocRoute: typeof AiPocRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  AiPocRoute: AiPocRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/ai-poc"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/ai-poc": {
      "filePath": "ai-poc.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
